
import com.mashape.unirest.http.*;
import com.mysql.cj.protocol.Resultset;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import moviedb.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
public class mainpanel extends javax.swing.JFrame implements ActionListener{

 
    public mainpanel() {
        initComponents();
        setSize(800,900);
        bt1.addActionListener(this);
        bt2.addActionListener(this);
        bt3.addActionListener(this);
        bt4.addActionListener(this);
        bt5.addActionListener(this);
        
        
        go();
    }
    static void go()
    {
        try
        {
            ResultSet rs=Dbloader.executeQuery("select * from favmovies");
            int x=10,y=10,k=0;
            while(rs.next())
            {
                k++;
                search_person_panel panel=new search_person_panel();
                 panel.setBounds(x,y,210,450);
                    if(k%3==0)
                    {
                        x=10;
                        y=y+470;
                    }
                    else
                    {
                        x+=220;
                    }
                panel.lb1.setText(rs.getString("name"));
                panel.lb2.setText(rs.getInt("id")+" ");
                ImageIcon im=new ImageIcon("src/pictures/war.jpeg");
                Image img=im.getImage().getScaledInstance(panel.lb3.getWidth(), panel.lb3.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon im1=new ImageIcon(img);
                panel.lb3.setIcon(im1);
                panel.ta1.setText(rs.getString("description"));
                panel.ta1.setLineWrap(true);
                mainpanel4.add(panel);
                //mainpanel2.repaint();
                panel.repaint(); 
            }
             mainpanel4.setPreferredSize(new Dimension(220*3,(k/2)*470));
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        lb2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainpanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb1.setText("BINGE WATCH");
        getContentPane().add(lb1);
        lb1.setBounds(280, 10, 200, 30);

        bt1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        bt1.setText("UPCOMING MOVIES");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(10, 50, 150, 30);

        bt2.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        bt2.setText("MOVIES");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(180, 50, 100, 30);

        bt3.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        bt3.setText("TV SHOWS");
        getContentPane().add(bt3);
        bt3.setBounds(300, 50, 100, 30);

        bt4.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        bt4.setText("SEARCH ACTOR");
        getContentPane().add(bt4);
        bt4.setBounds(420, 50, 150, 30);

        bt5.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        bt5.setText("COMPANY NAME");
        getContentPane().add(bt5);
        bt5.setBounds(590, 50, 130, 30);

        lb2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb2.setText("FAVORITES");
        getContentPane().add(lb2);
        lb2.setBounds(300, 90, 170, 30);

        javax.swing.GroupLayout mainpanel4Layout = new javax.swing.GroupLayout(mainpanel4);
        mainpanel4.setLayout(mainpanel4Layout);
        mainpanel4Layout.setHorizontalGroup(
            mainpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        mainpanel4Layout.setVerticalGroup(
            mainpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainpanel4);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 730, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton bt1;
    public static javax.swing.JButton bt2;
    public static javax.swing.JButton bt3;
    public static javax.swing.JButton bt4;
    public static javax.swing.JButton bt5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    public static javax.swing.JPanel mainpanel4;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void actionPerformed(ActionEvent e) 
    {
         
       if(e.getSource()==bt1)
       { 
           
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new upcoming_movies().setVisible(true);
            }
        });
       }
       else if(e.getSource()==bt2)
       {
           java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_movie().setVisible(true);
            }
        });
       

       }
       else if(e.getSource()==bt3)
       {
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_tv_shows().setVisible(true);
            }
        });
       }
       else if(e.getSource()==bt4)
       {
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_person().setVisible(true);
            }
        });
       }
       else if(e.getSource()==bt5)
       {
           java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_company().setVisible(true);
            }
        });
       }
    }
}
