
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author risha
 */
public class search_person_panel extends javax.swing.JPanel {

   
    public search_person_panel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        lb3 = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setLayout(null);

        lb1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lb1.setText("title");
        add(lb1);
        lb1.setBounds(10, 160, 170, 40);

        lb2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lb2.setText("rating");
        add(lb2);
        lb2.setBounds(10, 210, 140, 17);

        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 190, 180);
        add(lb3);
        lb3.setBounds(10, 10, 180, 150);

        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        add(bt1);
        bt1.setBounds(10, 420, 190, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        
       
    }//GEN-LAST:event_bt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton bt1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lb1;
    public javax.swing.JLabel lb2;
    public javax.swing.JLabel lb3;
    public javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables

   
}
