
import com.mashape.unirest.http.*;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
public class search_company extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form search_company
     */
    public search_company() {
        initComponents();
        setSize(800,600);
        bt1.addActionListener(this);
    }
      static void go(String name1)
    {
        mainpanel3.removeAll();
         String api = "980d96176457a6e65b8bc282bcadccd4";
        try 
        {
           
            HttpResponse<String> res = Unirest.get("https://api.themoviedb.org/3/search/company?api_key=980d96176457a6e65b8bc282bcadccd4&query="+name1+"&page=1").asString();
               
                    
            if(res.getStatus()==200)
            {
                String ans=res.getBody();
                JSONParser parser=new JSONParser();
                
                JSONObject mainobj=(JSONObject) parser.parse(ans);
                
                JSONArray array=(JSONArray) mainobj.get("results");
                
                 int x=10,y=10,k=0;
                 for(int i=0;i<array.size();i++)
                 {
                    k++;
                    JSONObject singleobj=(JSONObject)array.get(i);
                    String name=(String) singleobj.get("name");
                    
                    long id=(long) singleobj.get("id");
                    company_small_panel panel=new company_small_panel();
                    
                    panel.setBounds(x,y,210,300);
                    if(k%3==0)
                    {
                        x=10;
                        y=y+470;
                    }
                    else
                    {
                        x+=220;
                    }
                    
                    panel.lb2.setText("<html>"+name+"</html>");
                    panel.lb3.setText(id+"");
                    ImageIcon im=new ImageIcon("src/pictures/war.jpeg");
                    Image img=im.getImage().getScaledInstance(panel.lb1.getWidth(), panel.lb1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon im1=new ImageIcon(img);
                    panel.lb1.setIcon(im1);
                    
                    
                    mainpanel3.add(panel);
                    //mainpanel2.repaint();
                    panel.repaint(); 
                 }
                    
                    
                    
                
                mainpanel3.setPreferredSize(new Dimension(220*3,(k/2)*300));
            }
        }      
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainpanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb1.setText("SEARCH COMPANY");
        getContentPane().add(lb1);
        lb1.setBounds(180, 17, 314, 29);
        getContentPane().add(tf1);
        tf1.setBounds(30, 60, 230, 30);

        bt1.setText("SEARCH");
        getContentPane().add(bt1);
        bt1.setBounds(300, 60, 90, 30);

        javax.swing.GroupLayout mainpanel3Layout = new javax.swing.GroupLayout(mainpanel3);
        mainpanel3.setLayout(mainpanel3Layout);
        mainpanel3Layout.setHorizontalGroup(
            mainpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        mainpanel3Layout.setVerticalGroup(
            mainpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainpanel3);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 680, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bt1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private static javax.swing.JPanel mainpanel3;
    public javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent e) 
    {
        String name=tf1.getText();
        String name1=name.replace(" ","%20");
        tf1.setText("");
        tf1.requestFocus();
        go(name1);
    }
}
